config/routes.rb
Rails.application.routes.draw do
  namespace :user, path: '' do
    root 'top#index'
    get 'login' => 'sessions#new', as: :login
    resource :session, only: %i[create destroy]

    get 'home' => 'top#home', as: :home
    resource :account, only: %i[show edit update]
    resource :profile, only: %i[show edit update]
    resource :password, only: %i[show edit update]
    resources :activities, except: %i[new] do
      collection do
        get 'commit/new', action: 'new_commit'
        get 'result/new', action: 'new_result'
      end
      member do
        post 'abort', action: 'abort'
        post 'done', action: 'done'
        post 'ready', action: 'ready'
        get 'record', action: 'record'
      end
    end
    resources :achievements, only: %i[index show]
    resources :gyms, only: %i[index show]
    resources :relationships, only: %i[create destroy]

    resources :users do
      resources :activities,    only: %i[index show]
      resources :achievements,  only: %i[index show]
      member do
        get :following, :followers
      end
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  experience      :string
#  frequency       :string
#  introduction    :string
#  level           :string
#  name            :string           not null
#  password_digest :string           not null
#  status          :string           default("stable"), not null
#  uid             :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  gym_id          :bigint
#
# Indexes
#
#  index_users_on_LOWER_email  (lower((email)::text)) UNIQUE
#  index_users_on_LOWER_uid    (lower((uid)::text)) UNIQUE
#  index_users_on_gym_id       (gym_id)
#
# Foreign Keys
#
#  fk_rails_...  (gym_id => gyms.id)
#
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { maximum: 50 }

  include UserIdHolder
  # TODO: 最小文字数指定するとuser情報編集時になぜかエラー
  # include PasswordHolder
  include EmailHolder

  # rerationship
  has_many :active_relationships,  class_name: 'Relationship',
                                   foreign_key: 'follower_id',
                                   dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # activity
  has_many :activities, dependent: :destroy, autosave: true

  # mygym
  belongs_to :gym, optional: true

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # ユーザーのアクティビティフィードを返す
  def feed
    following_ids = 'SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id'
    Activity.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end
end

app/controllers/user/accounts_controller.rb
class User::AccountsController < User::Base
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    if @user.save
      flash.notice = 'アカウント情報を更新しました。'
      redirect_to :user_account
    else
      render action: 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :uid, :email
    )
  end
end

app/controllers/user/achievements_controller.rb
class User::AchievementsController < User::Base
  def index
    @message = '準備中'
  end

  def show; end
end

app/controllers/user/activities_controller.rb
class User::ActivitiesController < User::Base
  before_action :access_auth, only: %i[edit update abort done ready record]

  def index
    @user = params[:user_id] ? User.find(params[:user_id]) : current_user
    @activities = @user.activities.order(date: :desc).includes(:gym)
  end

  def show
    @activity = Activity.find(params[:id])
    @gym = @activity.gym
    return unless @activity.status == Settings.activity.status.recorded

    # 結果レベル情報の取得
    @lc_attr = @activity.level_count.attributes.values[2..11]
    @ln_attr = @gym.level_name.attributes.values[2..11]
  end

  def new_commit
    @activity_form = User::ActivityForm.new(current_user.id)
    render action: 'new'
  end

  def new_result
    @activity_form = User::ActivityForm.new(current_user.id)
    @activity_form.activity.status = Settings.activity.status.recorded
    render action: 'new'
  end

  def create
    @activity_form = User::ActivityForm.new(current_user.id)
    @activity_form.assign_attributes(params)

    if @activity_form.save
      flash.notice = 'アクティビティを追加しました。'
      redirect_to action: 'index'
    else
      flash.now.alert = '入力に誤りがあります。'
      render action: 'new'
    end
  end

  def edit
    @activity_form = User::ActivityForm.new(current_user.id, Activity.find(params[:id]))
  end

  def update
    @activity_form = User::ActivityForm.new(current_user.id, Activity.find(params[:id]))
    @activity_form.assign_attributes(params)

    if @activity_form.save
      flash.notice = 'アクティビティを更新しました。'
      redirect_to action: 'index'
    else
      flash.now.alert = '入力に誤りがあります。'
      render action: 'edit'
    end
  end

  def destroy
    activity_form = Activity.find(params[:id])
    activity_form.destroy!
    flash.notice = 'アクティビティを削除しました。'
    redirect_to :user_activities
  end

  def abort
    activity = Activity.find(params[:id])
    return if activity.status != Settings.activity.status.ready

    activity.status = Settings.activity.status.aborted
    if activity.save
      flash.notice = 'アクティビティを中止しました。'
    else
      flash.alert = activity.errors.first[1]
    end
    redirect_to :user_activities
  end

  def done
    activity = Activity.find(params[:id])
    return if activity.status != Settings.activity.status.ready

    activity.status = Settings.activity.status.done
    if activity.save
      flash.notice = 'アクティビティを完了しました。'
    else
      flash.alert = activity.errors.first[1]
    end
    redirect_to :user_activities
  end

  def ready
    activity = Activity.find(params[:id])
    return if activity.status != Settings.activity.status.aborted

    activity.status = Settings.activity.status.ready
    if activity.save
      flash.notice = 'アクティビティを再開しました。'
    else
      flash.alert = activity.errors[:status].first
    end
    redirect_to :user_activities
  end

  def record
    activity = Activity.find(params[:id])
    return redirect_to :user_activities if activity.status != Settings.activity.status.done

    activity.status = Settings.activity.status.recorded
    @activity_form = User::ActivityForm.new(current_user.id, activity)
    render action: 'edit'
  end

  private

  def access_auth
    owner = Activity.find(params[:id]).user
    return if current_user == owner

    flash.alert = '編集権限がありません。'
    redirect_back(fallback_location: :user_home)
  end
end

app/controllers/user/base.rb
class User::Base < ApplicationController
  before_action :authorize
  before_action :check_timeout

  helper_method :current_user

  private

  # ユーザログインのセッション情報
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # セッションによるフィルタリング
  def authorize
    return if current_user

    flash.alert = 'ログインしてください。'
    redirect_to :user_login
  end

  TIMEOUT = 60.minutes
  # セッションタイムアウトの設定
  def check_timeout
    return unless current_user

    if session[:last_access_time] >= TIMEOUT.ago
      session[:last_access_time] = Time.current
    else
      session.delete(:user_id)
      flash.alert = 'セッションがタイムアウトしました。'
      redirect_to :user_login
    end
  end
end

app/controllers/user/gyms_controller.rb
class User::GymsController < User::Base
  skip_before_action :authorize

  def index
    @gyms = Gym.all
  end

  def show
    @gym = Gym.find(params[:id])
  end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < User::Base
  def show
    redirect_to :edit_user_password
  end

  def edit
    @change_password_form = User::ChangePasswordForm.new(object: current_user)
  end

  def update
    @change_password_form = User::ChangePasswordForm.new(user_member_params)
    @change_password_form.object = current_user
    if @change_password_form.save
      flash.notice = 'パスワードを変更しました。'
      redirect_to :user_account
    else
      flash.alert = '入力に誤りがあります。'
      render action: 'edit'
    end
  end

  private

  def user_member_params
    params.require(:user_change_password_form).permit(
      :current_password, :new_password, :new_password_confirmation
    )
  end
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < User::Base
  def show
    @user = current_user
  end

  def edit
    @user = current_user
    @gyms = Gym.all
    @mygym_id = @user.gym&.id
  end

  def update
    @user = current_user
    @user.assign_attributes(user_params)
    if @user.save
      flash.notice = 'プロフィールを更新しました。'
      redirect_to :user_profile
    else
      render action: 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name, :experience, :frequency, :level, :gym_id, :introduction
    )
  end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < User::Base
  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to [:user, user]
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to [:user, user]
  end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < User::Base
  skip_before_action :authorize

  def new
    if current_user
      redirect_to :user_home
    else
      @form = User::LoginForm.new
      render action: 'new'
    end
  end

  def create
    @form = User::LoginForm.new(login_form_params)
    user = User.find_by('LOWER(email) = ?', @form.email.downcase) if @form.email.present?
    if user&.authenticate(@form.password)
      session[:user_id] = user.id
      session[:last_access_time] = Time.current
      flash.notice = 'ログインしました。'
      redirect_to :user_home
    else
      flash.now.alert = 'メールアドレスまたはパスワードが正しくありません。'
      render action: 'new'
    end
  end

  # ログアウト
  def destroy
    session.delete(:user_id)
    flash.notice = 'ログアウトしました。'
    redirect_to :user_login
  end

  private

  def login_form_params
    params.require(:user_login_form).permit(:email, :password)
  end
end

app/controllers/user/top_controller.rb
class User::TopController < User::Base
  skip_before_action :authorize, only: %i[index]

  def index
    if current_user.nil?
      render action: 'index'
    else
      redirect_to :user_home
    end
  end

  def home
    @feed_items = current_user.feed.order(updated_at: :desc)
  end
end

app/controllers/user/users_controller.rb
class User::UsersController < User::Base
  skip_before_action :authorize, only: %i[new create]
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name = user_params[:uid]
    if @user.save
      session[:user_id] = @user.id
      session[:last_access_time] = Time.current
      redirect_to :user_home
    else
      render action: 'new'
    end
  end

  def following
    @title = 'Following'
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :uid)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    link_to image_tag(gravatar_url, alt: user.name, class: 'gravatar'), [:user, user]
  end
end

app/views/user/users/_follow.html.erb
<%= form_with(model: [:user, current_user.active_relationships.build]) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/user/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/user/users/_form.html.erb
<%= markup do |m|
  p = UserFormPresenter.new(f, self)
  m << p.notes
  p.with_options(required: true, class: 'form-control') do |q|
    m << q.email_field_block(:email, "メールアドレス")
    m << q.password_field_block(:password, "パスワード")
    m << q.password_field_block(:password_confirmation, "パスワード（確認）")
    m << q.text_field_block(:uid, "ID")
  end
end %>

app/views/user/users/_unfollow.html.erb
<%= form_with(model: [:user, current_user.active_relationships.find_by(followed_id: @user.id)],
              html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/user/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, [:user, user] %>
</li>

app/views/user/users/index.html.erb
<% @title = 'ボル友を探す'%>
<h1><%= @title %></h1>

<div class='table-wrapper'>
  <table class='listing'>
    <thead class='thead-dark'>
      <tr>
        <th></th>
        <th>ID</th>
        <th>名前</th>
        <th>status</th>
        <th></th>
      </tr>
    </thead>
    <% @users.each do |u| %>
      <tr>
        <td><%= gravatar_for u, size: 50 %></td>
        <td><%= "@#{u.uid}" %></td>
        <td><%= u.name %></td>
        <td><%= u.status %></td>
        <td class='actions'>
          <%= link_to '詳細', user_users_path + "/#{u.id}"%>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/user/users/new.html.erb
<% @title = '新規登録'%>
<h1><%= @title %></h1>

<fieldset>
  <div class='form-group' id='generic-form'>
    <%= form_with model: @user, url: :user_users do |f| %>
      <%= render 'form', f: f %>
      <div class='button'>
        <%= f.submit '登録' , class: "btn btn-lg btn-primary btn-block btn-submit" %>
        <%= link_to 'キャンセル', :user_login, class: "btn btn-lg btn-block btn-cancel"  %>
      </div>
    <% end %>
  </div>
</fieldset>

app/views/user/users/show.html.erb
<% @title = '@' + @user.uid %>
<% provide(:title, @user.name) %>

<fieldset id='user-profile' class='card card-container'>
  <div class='user-icon'>
    <%= gravatar_for @user, size: 160%>
  </div>
  <div class='profile'>
    <h2><%= link_to "@#{@user.uid}", [:user, @user] %></h2>
    <h3><%= "#{@user.name}さん" %></h3>
    <div class='introduction'>
      <p><%= @user.introduction %></p>
    </div>
  </div>

  <section class='stats'>
    <%= render 'user/shared/stats' %>
  </section>
  <%= render 'follow_form' if current_user %>
  <% if @user %>
    <div class='user_menu' >
      <%= link_to 'アクティビティ', [:user, @user, :activities], class: 'btn btn-primary', role: 'button' %>
      <%= link_to 'アチーブメント', [:user, @user, :achievements], class: 'btn btn-primary', role: 'button' %>
    </div>
  <% end  %>
</fieldset>

app/views/user/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class='row'>
  <aside class='col-md-4'>
    <section class='user_info'>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
    </section>

    <section class='stats'>
      <%= render 'user/shared/stats' %>
      <% if @users.any? %>
        <div class='user_avatars'>
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), [:user, @user] %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class='col-md-8'>
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class='users follow'>
        <%= render @users %>
      </ul>
    <% end %>
  </div>
</div>